### PR TITLE
Add Home Assistant MQTT auto discovery + improvements

### PR DESCRIPTION
**Pull request by sehraf**
Hi,

this PR implements MQTT [auto discovery](https://www.home-assistant.io/docs/mqtt/discovery/) which is used by Home Assistant (can be enabled by the define `ENABLE_HOMEASSISTANT`). It further replaces [PubSubClient](https://github.com/knolleary/pubsubclient) by [AsyncMqttClient](https://github.com/marvinroger/async-mqtt-client) and restructures how WiFi is handled (which greatly improves connection stability here).
The old behavior is still supported so this should be a drop-in replacement.

The changes are loosely based on [McLighting](https://github.com/toblum/McLighting). Since i have moved the file (see first commit) the overall diff is pretty useless :disappointed: 

I'm still waiting for my WiFi Relay boards to be shipped so this is not tested on real hardware but *only* on a NodeMCU.

Lastly, **thank you** for this project as i prefer to keep the hardware as it is :wink:

### CODE REVIEW

**Comment by doleron** [comment]
Hi, @sehraf ! First of all, thank you very much for the PR. I look at your code and it looks good. Unfortunately I'm travelling/vacancy right now and I haven't how to test it in the proper relay board myself. Let me know when you have the board with you just for perform some practical tests. Another point  I have in mind is to make this repository as simple as possible in order to provide a basic raw example how to communicate with the board. So, if you agree, we can provide two folders/.ino files one for the basic version (maybe with wifi improvements & async) and the other one for the one with home assistant support. Let me know what you think about it. Kind regards, Luiz.

**Comment by sehraf** [comment]
Hi, 
my boards should arrive any time now. 
I'm fine with any kind of providing different versions. As a suggestion: You can also uses releases. E.g. you could release the current version and then merge the PR and release a second version. Did you plan on removing the HA code in one version? I'm asking because changing one line from `1` to `0` does that (and somebody who is able to compile the code should be able to edit one line :wink: )
Anyway, i've also continued working on the code to add support for the board with two relays (the code support any amount of relays). Again i'm waiting for my boards :upside_down_face: 

A note on ~wifi~ MQTT problems: My NodeMCU board was loosing connection to the MQTT server all the time and mostly failed to reestablish it, ending in multiple ongoing connection attempts at the same time. No idea if this is a local problem of my setting or a side effect of the code. Maybe you have seen similar?

Anyway, lets wait until *someone* can properly test the code :rocket:

**Comment by sehraf** [comment]
So i got my board and finally figured out what flash it has ....
The last commit switches the operations and the initial state for Home Assistant.
When powering the board the LED on the relay board itself is off and this equals `off` in HA now (the internal state is `OPEN`). Turning it on through HA sends `CLOSE` which toggles the relay and turns on the blue LED on the relay board.
I would call this matching but we can discuss this. No idea if there is a fixed definition if the default state of a relay is called "open" or "close" :laughing: 

Beside this everything is working as expected.

**Comment by sehraf** [comment]
So i got my board and finally figured out what flash it has ....
The last commit switches the operations and the initial state for Home Assistant.
When powering the board the LED on the relay board itself is off and this equals `off` in HA now (the internal state is `OPEN`). Turning it on through HA sends `CLOSE` which toggles the relay and turns on the blue LED on the relay board.
I would call this matching but we can discuss this. No idea if there is a fixed definition if the default state of a relay is called "open" or "close" :laughing: 

Beside this everything is working as expected.

**Comment by sehraf** [comment]
The last commit add support for multiple relays on one board.
Tested with single, double and quad relay boards.

**Comment by doleron** [comment]
Hi @sehraf I just merged your code. Thank you for the contribution and feel free to submit new PRs for any improvement.

**Pull request merged**
